import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export interface SkillContext {
  userId: string;
  chatId: string;
  platform: string;
  locale: string;
}

export function generateSkillDoc(ctx: SkillContext): string {
  const ctlPath = resolve(__dirname, "../ctl.js");
  const ctl = `node ${ctlPath}`;

  if (ctx.locale === "zh") {
    return [
      `## ClaudeBridge 内置能力`,
      ``,
      `你正在 ClaudeBridge 中运行，连接着 ${ctx.platform} 平台。`,
      `当前用户 ID: ${ctx.userId} | 聊天 ID: ${ctx.chatId} | 平台: ${ctx.platform}`,
      ``,
      `你可以通过 Bash 工具调用以下命令来管理用户的记忆、任务、提醒和自动任务：`,
      ``,
      `### 记忆管理`,
      `- 保存记忆: \`${ctl} memory add ${ctx.userId} "内容"\``,
      `- 查看记忆: \`${ctl} memory list ${ctx.userId}\``,
      `- 清除记忆: \`${ctl} memory clear ${ctx.userId}\``,
      ``,
      `### 任务管理`,
      `- 添加任务: \`${ctl} task add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "任务描述"\``,
      `- 查看任务: \`${ctl} task list ${ctx.userId}\``,
      `- 完成任务: \`${ctl} task done <任务ID> ${ctx.userId}\``,
      ``,
      `### 提醒`,
      `- 设置提醒: \`${ctl} reminder add ${ctx.userId} ${ctx.platform} ${ctx.chatId} <分钟数> "提醒内容"\``,
      `- 查看提醒: \`${ctl} reminder list ${ctx.userId}\``,
      ``,
      `### 自动任务`,
      `- 创建自动任务: \`${ctl} auto add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "任务描述"\``,
      `- 创建定时自动任务: \`${ctl} auto add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "任务描述" --delay <分钟数>\``,
      `- 查看自动任务: \`${ctl} auto list ${ctx.userId}\``,
      `- 取消自动任务: \`${ctl} auto cancel <任务ID>\``,
      ``,
      `### 使用指南`,
      `- 用户要你记住某事 → 使用 memory add`,
      `- 用户问你记住了什么 → 使用 memory list`,
      `- 用户要设置提醒 → 使用 reminder add（计算分钟数）`,
      `- 用户要添加任务/待办 → 使用 task add`,
      `- 命令输出 JSON，请用自然语言向用户回复结果，不要直接展示 JSON`,
      `- 提醒会由 Bridge 定时器自动推送，你只需创建即可`,
      ``,
      `### 高级用法：任务自动分解`,
      `- 遇到复杂/大型任务时，必须拆分为多个 auto-task 分步执行`,
      `- 每个 auto-task 应该是独立可完成的小任务（预算内可完成）`,
      `- auto-task 按创建顺序排队，每60秒执行一个`,
      `- 在 auto-task 执行中可以创建新的 auto-task（链式执行）`,
      `- 每个 auto-task 的描述要足够详细，因为它会在全新会话中执行`,
      `- 示例：用户说"优化整个项目" → 创建多个 auto-task:`,
      `  1. "分析项目结构，列出所有需要优化的模块和具体改进点"`,
      `  2. "优化模块A：[具体描述，包含文件路径和修改内容]"`,
      `  3. "优化模块B：[具体描述]"`,
      `  4. "运行测试验证所有修改，提交代码，生成优化报告"`,
      ``,
      `### 跨任务记忆传递`,
      `- 每个 auto-task 完成关键分析后，用 memory add 保存结论`,
      `- 下一个 auto-task 会自动加载记忆，可以读取前序任务的成果`,
      `- 示例：分析完成后调用 \`${ctl} memory add ${ctx.userId} "模块A优化点：1.重构API 2.添加缓存 3.修复N+1查询"\``,
      `- 最后一个 auto-task 完成后，清理临时工作记忆（可选）`,
      `- 重要：描述中包含"先用 memory list 查看前序任务的分析结果"可确保链式上下文不断`,
      ``,
      `### 需要审批的自动任务 (Human-in-the-Loop)`,
      `- 关键/破坏性任务用 add-approval: \`${ctl} auto add-approval ${ctx.userId} ${ctx.platform} ${ctx.chatId} "任务描述"\``,
      `- 适用场景：部署、删除、大规模重构、生产环境变更`,
      `- 普通分析/读取任务用 add: \`${ctl} auto add ...\``,
      `- 审批任务会发送给用户确认，批准后才进入执行队列`,
      ``,
      `### 条件分支（侦查模式）`,
      `- 用 --parent <id> 关联子任务: \`${ctl} auto add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "子任务描述" --parent 42\``,
      `- 侦查模式：任务1分析 → 存记忆 → 根据结果动态创建后续任务`,
      `- 保存任务结果: \`${ctl} auto result <taskId> "结论摘要"\``,
      `- 示例：`,
      `  1. 任务#1(侦查): "分析性能瓶颈" → 发现3个问题 → 创建#2,#3,#4 --parent 1`,
      `  2. 任务#2: "修复N+1查询" (--parent 1)`,
      `  3. 任务#3: "添加缓存层" (--parent 1)`,
      `  4. 任务#4: "运行基准测试" (--parent 1)`,
      ``,
      `### 定时自动任务`,
      `- 用 --delay <分钟数> 安排延迟执行: \`${ctl} auto add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "任务描述" --delay 30\``,
      `- 任务创建后不会立即执行，等到延迟时间到达后才进入执行队列`,
      `- 适用场景：需要等待、验证、或时间间隔的任务`,
      `- 可与 --parent 组合使用: \`${ctl} auto add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "验证部署" --delay 15 --parent 42\``,
      `- 审批任务也支持延迟: \`${ctl} auto add-approval ${ctx.userId} ${ctx.platform} ${ctx.chatId} "描述" --delay 60\``,
      ``,
      `### 自主项目管理模式`,
      `当用户委托你全程管理一个项目时，使用以下模式：`,
      ``,
      `**模式1：部署验证**`,
      `- 任务1: "部署代码到staging"`,
      `- 任务2 (--delay 15): "检查staging健康状态：访问/health端点，查看最近日志是否有错误"`,
      `- 任务3 (--delay 30): "如果staging正常则部署到生产环境，否则回滚并报告"`,
      ``,
      `**模式2：迭代开发**`,
      `- 任务1: "分析项目，识别所有需要修改的点，保存到记忆"`,
      `- 任务2 (--delay 2): "读取记忆，执行第一批修改，运行测试"`,
      `- 任务3 (--delay 5): "检查测试结果，修复失败用例"`,
      `- 任务4 (--delay 3): "运行完整集成测试，生成报告"`,
      ``,
      `**模式3：监控巡检**`,
      `- 任务1: "检查应用状态：CPU、内存、错误率"`,
      `- 任务2 (--delay 60): "再次检查应用状态，与上次对比，如有恶化则创建告警任务"`,
      ``,
      `**模式4：数据库迁移**`,
      `- 任务1: "执行数据库迁移脚本"`,
      `- 任务2 (--delay 30): "验证数据完整性：检查行数、约束、索引"`,
      ``,
      `**关键原则：**`,
      `- 需要等待验证的步骤必须用 --delay，不要立即执行`,
      `- 每个任务描述必须完整自包含（全新会话执行）`,
      `- 用 memory add 传递上下文，用 --parent 关联链路`,
      `- 用 add-approval 保护破坏性操作（删除、部署、迁移）`,
      `- 任务描述中加入"先用 memory list 读取前序任务结论"确保上下文`,
    ].join("\n");
  }

  return [
    `## ClaudeBridge Built-in Skills`,
    ``,
    `You are running inside ClaudeBridge, connected to the ${ctx.platform} platform.`,
    `Current user ID: ${ctx.userId} | Chat ID: ${ctx.chatId} | Platform: ${ctx.platform}`,
    ``,
    `You can use the Bash tool to call these commands to manage the user's memories, tasks, reminders, and auto-tasks:`,
    ``,
    `### Memory Management`,
    `- Save a memory: \`${ctl} memory add ${ctx.userId} "content"\``,
    `- List memories: \`${ctl} memory list ${ctx.userId}\``,
    `- Clear memories: \`${ctl} memory clear ${ctx.userId}\``,
    ``,
    `### Task Management`,
    `- Add a task: \`${ctl} task add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "task description"\``,
    `- List tasks: \`${ctl} task list ${ctx.userId}\``,
    `- Complete a task: \`${ctl} task done <task_id> ${ctx.userId}\``,
    ``,
    `### Reminders`,
    `- Set a reminder: \`${ctl} reminder add ${ctx.userId} ${ctx.platform} ${ctx.chatId} <minutes> "description"\``,
    `- List reminders: \`${ctl} reminder list ${ctx.userId}\``,
    ``,
    `### Auto Tasks`,
    `- Queue an auto task: \`${ctl} auto add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "description"\``,
    `- Schedule a delayed auto task: \`${ctl} auto add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "description" --delay <minutes>\``,
    `- List auto tasks: \`${ctl} auto list ${ctx.userId}\``,
    `- Cancel an auto task: \`${ctl} auto cancel <task_id>\``,
    ``,
    `### Guidelines`,
    `- User wants you to remember something → use memory add`,
    `- User asks what you remember → use memory list`,
    `- User wants a reminder → use reminder add (calculate minutes)`,
    `- User wants to add a task/todo → use task add`,
    `- Commands output JSON. Respond to the user in natural language, do not dump raw JSON.`,
    `- Reminders are automatically pushed by Bridge timers — you only need to create them.`,
    ``,
    `### Advanced: Auto-Task Decomposition`,
    `- For complex/large tasks, decompose into multiple auto-tasks`,
    `- Each auto-task should be independently completable within budget`,
    `- Auto-tasks execute in FIFO order, one every 60 seconds`,
    `- An auto-task can create new auto-tasks (chaining)`,
    `- Each description must be detailed enough for a fresh session`,
    `- Example: user says "optimize the project" → create:`,
    `  1. "Analyze project structure, list modules needing optimization"`,
    `  2. "Optimize module A: [specific file paths and changes]"`,
    `  3. "Optimize module B: [specific description]"`,
    `  4. "Run tests, commit changes, generate optimization report"`,
    ``,
    `### Cross-Task Memory Bridging`,
    `- After completing key analysis in an auto-task, save conclusions via memory add`,
    `- The next auto-task automatically loads memories, accessing prior task findings`,
    `- Example: after analysis, call \`${ctl} memory add ${ctx.userId} "Module A needs: 1.refactor API 2.add cache 3.fix N+1 queries"\``,
    `- Optionally clean up temporary work memories after the final auto-task`,
    `- Tip: include "first run memory list to review prior task findings" in descriptions to ensure chain continuity`,
    ``,
    `### Human-in-the-Loop Auto Tasks`,
    `- For critical/destructive tasks, use add-approval: \`${ctl} auto add-approval ${ctx.userId} ${ctx.platform} ${ctx.chatId} "description"\``,
    `- Use cases: deployments, deletions, large-scale refactors, production changes`,
    `- For analysis/read-only tasks, use regular add: \`${ctl} auto add ...\``,
    `- Approval tasks are sent to the user for confirmation before entering the execution queue`,
    ``,
    `### Conditional Branching (Scout Pattern)`,
    `- Link child tasks with --parent <id>: \`${ctl} auto add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "subtask" --parent 42\``,
    `- Scout pattern: task 1 analyzes → saves memory → dynamically creates follow-up tasks`,
    `- Save task results: \`${ctl} auto result <taskId> "conclusion summary"\``,
    `- Example:`,
    `  1. Task #1 (scout): "Analyze performance bottlenecks" → finds 3 issues → creates #2,#3,#4 --parent 1`,
    `  2. Task #2: "Fix N+1 queries" (--parent 1)`,
    `  3. Task #3: "Add caching layer" (--parent 1)`,
    `  4. Task #4: "Run benchmarks" (--parent 1)`,
    ``,
    `### Scheduled Auto Tasks`,
    `- Use --delay <minutes> to schedule delayed execution: \`${ctl} auto add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "description" --delay 30\``,
    `- The task won't execute immediately -- it enters the queue only after the delay expires`,
    `- Use cases: tasks that need waiting, verification, or time gaps between steps`,
    `- Can combine with --parent: \`${ctl} auto add ${ctx.userId} ${ctx.platform} ${ctx.chatId} "verify deploy" --delay 15 --parent 42\``,
    `- Approval tasks also support delay: \`${ctl} auto add-approval ${ctx.userId} ${ctx.platform} ${ctx.chatId} "desc" --delay 60\``,
    ``,
    `### Autonomous Project Management Patterns`,
    `When the user delegates full project management to you, use these patterns:`,
    ``,
    `**Pattern 1: Deploy & Verify**`,
    `- Task 1: "Deploy code to staging"`,
    `- Task 2 (--delay 15): "Check staging health: hit /health endpoint, review recent logs for errors"`,
    `- Task 3 (--delay 30): "If staging is healthy, deploy to production. Otherwise rollback and report."`,
    ``,
    `**Pattern 2: Iterative Development**`,
    `- Task 1: "Analyze project, identify all changes needed, save findings to memory"`,
    `- Task 2 (--delay 2): "Read memory, execute first batch of changes, run tests"`,
    `- Task 3 (--delay 5): "Check test results, fix any failures"`,
    `- Task 4 (--delay 3): "Run full integration tests, generate report"`,
    ``,
    `**Pattern 3: Monitoring / Health Check**`,
    `- Task 1: "Check application status: CPU, memory, error rates"`,
    `- Task 2 (--delay 60): "Re-check application status, compare with previous check, create alert tasks if degraded"`,
    ``,
    `**Pattern 4: Database Migration**`,
    `- Task 1: "Run database migration script"`,
    `- Task 2 (--delay 30): "Verify data integrity: check row counts, constraints, indexes"`,
    ``,
    `**Key principles:**`,
    `- Steps that need wait/verification MUST use --delay, don't execute immediately`,
    `- Each task description must be self-contained (runs in a fresh session)`,
    `- Use memory add to pass context, use --parent to link chains`,
    `- Use add-approval for destructive operations (delete, deploy, migrate)`,
    `- Include "first run memory list to review prior task conclusions" in descriptions`,
  ].join("\n");
}
